/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Month = bigint;
export interface MonthlyRecord {
  'month' : Month,
  'payments' : Array<Payment>,
  'workedHours' : bigint,
  'transportAllowanceCents' : bigint,
  'year' : Year,
  'hourlyRateCents' : bigint,
  'totalDueCents' : bigint,
}
export interface Payment {
  'date' : Time,
  'amountCents' : bigint,
  'paymentType' : PaymentType,
}
export type PaymentType = { 'bank' : null } |
  { 'cash' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'defaultHourlyRateCents' : bigint,
  'defaultTransportAllowanceCents' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Year = bigint;
export interface _SERVICE {
  'addPayment' : ActorMethod<[Month, Year, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateMonthlyRecord' : ActorMethod<
    [Month, Year, bigint, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'deleteMonthlyRecord' : ActorMethod<[Month, Year], undefined>,
  'deletePayment' : ActorMethod<[Month, Year, Time], undefined>,
  'getAllRecords' : ActorMethod<[], Array<MonthlyRecord>>,
  'getAllSummaries' : ActorMethod<
    [],
    Array<[Month, Year, bigint, bigint, bigint]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMonthlyRecord' : ActorMethod<[Month, Year], MonthlyRecord>,
  'getPaymentsForMonth' : ActorMethod<[Month, Year], Array<Payment>>,
  'getSummary' : ActorMethod<[Month, Year], [bigint, bigint, bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasExistingPayments' : ActorMethod<[Month, Year], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];