/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Month = IDL.Nat;
export const Year = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentType = IDL.Variant({
  'bank' : IDL.Null,
  'cash' : IDL.Null,
});
export const Payment = IDL.Record({
  'date' : Time,
  'amountCents' : IDL.Nat,
  'paymentType' : PaymentType,
});
export const MonthlyRecord = IDL.Record({
  'month' : Month,
  'payments' : IDL.Vec(Payment),
  'workedHours' : IDL.Nat,
  'transportAllowanceCents' : IDL.Nat,
  'year' : Year,
  'hourlyRateCents' : IDL.Nat,
  'totalDueCents' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'defaultHourlyRateCents' : IDL.Nat,
  'defaultTransportAllowanceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPayment' : IDL.Func([Month, Year, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateMonthlyRecord' : IDL.Func(
      [Month, Year, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'deleteMonthlyRecord' : IDL.Func([Month, Year], [], []),
  'deletePayment' : IDL.Func([Month, Year, Time], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(MonthlyRecord)], ['query']),
  'getAllSummaries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Month, Year, IDL.Nat, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthlyRecord' : IDL.Func([Month, Year], [MonthlyRecord], ['query']),
  'getPaymentsForMonth' : IDL.Func(
      [Month, Year],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getSummary' : IDL.Func(
      [Month, Year],
      [IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasExistingPayments' : IDL.Func([Month, Year], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Month = IDL.Nat;
  const Year = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PaymentType = IDL.Variant({ 'bank' : IDL.Null, 'cash' : IDL.Null });
  const Payment = IDL.Record({
    'date' : Time,
    'amountCents' : IDL.Nat,
    'paymentType' : PaymentType,
  });
  const MonthlyRecord = IDL.Record({
    'month' : Month,
    'payments' : IDL.Vec(Payment),
    'workedHours' : IDL.Nat,
    'transportAllowanceCents' : IDL.Nat,
    'year' : Year,
    'hourlyRateCents' : IDL.Nat,
    'totalDueCents' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'defaultHourlyRateCents' : IDL.Nat,
    'defaultTransportAllowanceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPayment' : IDL.Func([Month, Year, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateMonthlyRecord' : IDL.Func(
        [Month, Year, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'deleteMonthlyRecord' : IDL.Func([Month, Year], [], []),
    'deletePayment' : IDL.Func([Month, Year, Time], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(MonthlyRecord)], ['query']),
    'getAllSummaries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Month, Year, IDL.Nat, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthlyRecord' : IDL.Func([Month, Year], [MonthlyRecord], ['query']),
    'getPaymentsForMonth' : IDL.Func(
        [Month, Year],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getSummary' : IDL.Func(
        [Month, Year],
        [IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasExistingPayments' : IDL.Func([Month, Year], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };